name: Deploy Serverless (CFN)

on:
  push:
    branches: [ "dev" ]   # körs när du pushar till dev-branch
  workflow_dispatch:       # gör att du kan starta manuellt i Actions-fliken

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://serverless-app/serverless-hello.yaml

      - name: Deploy stack
        run: |
          aws cloudformation deploy \
            --stack-name ${{ secrets.CF_STACK_NAME }} \
            --template-file serverless-app/serverless-hello.yaml \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset
